<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CentroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $centros = [
            ['centro' => 60, 
            'nombre' => 'Instituto de innovación en biosistemas para el desarrollo sustentable en zonas áridas.',
            'coordinador' => 'LOPEZ SANTIAGO MARCO ANDRES', 'ubpp_id' => 15, 'proy_ptal' => 602
            ],
            ['centro' => 61, 
            'nombre' => 'Instituto de politicas publicas e innovación agroalimentaria (ippia).',
            'coordinador' => 'DR.JUAN ANTONIO LEOS RODRIGUEZ', 'ubpp_id' => 41, 'proy_ptal' => 604,
            ],
            ['centro' => 62, 
            'nombre' => 'Instituto de alimentos (idea)',
            'coordinador' => 'DR. ARTEMIO PEREZ LOPEZ', 'ubpp_id' => 8, 'proy_ptal' => 605,
            ],
            ['centro' => 63, 
            'nombre' => 'Instituto de investigación y posgrado en protección fitosanitaria (iippf)',
            'coordinador' => 'DR. ANDRES BOLAÑOS ESPINOZA', 'ubpp_id' => 10, 'proy_ptal' => 608,
            ],
            ['centro' => 64, 
            'nombre' => 'Instituto de investigaciones socioambientales, educativas y humanisticas para el medio rural (iisehmer).',
            'coordinador' => 'DR. LIBERIO VICTORINO RAMIREZ', 'ubpp_id' => 12, 'proy_ptal' => 615,
            ],
            ['centro' => 65, 'nombre' => 'Instituto de ingenieria agricola y uso integral del agua (iiauia).',
            'coordinador' => 'DR. EFREN FITZ RODRIGUEZ', 'ubpp_id' => 9, 'proy_ptal' => 603,
            ],
            ['centro' => 66, 'nombre' => 'Instituto de horticultura',
            'coordinador' => 'DR. ALEJANDRO FACUNDO BARRIENRTOS PRIEGO', 'ubpp_id' => 7, 'proy_ptal' => 601,
            ],
            ['centro' => 67, 'nombre' => 'Instituto de investigación y posgrasdob en ciencia animal (iipca)',
            'coordinador' => 'DR. ALEJANDRO LARA BUENO', 'ubpp_id' => 14, 'proy_ptal' => 606,
            ],
            ['centro' => 68, 'nombre' => 'Instituto de investigaciones para la agricultura regional y el desarrollo rural (iiareder).',
            'coordinador' => 'DRA. MIRIAM AIDE NUÑEZ VERA', 'ubpp_id' => 36, 'proy_ptal' => 607,
            ],
            ['centro' => 72, 'nombre' => 'Centro de investigación en cultivos basicos. (cicuba)',
            'coordinador' => 'DR. ARTURO CHONG ESLAVA ', 'ubpp_id' => 7, 'proy_ptal' => 612,
            ],
            ['centro' => 73, 'nombre' => 'Centro de investigación en recursos naturales y medio ambiente (cirenam)',
            'coordinador' => 'DR. ALEJANDRO ISMAEL MONTERROSO RIVAS', 'ubpp_id' => 13, 'proy_ptal' => 613,
            ],
            ['centro' => 82, 'nombre' => 'Centro de investigaciones interdisiplinarias y de servicio en ciencia, naturaleza, sociedad y cultura (ciiscinasyc)',
            'coordinador' => 'DR. LUIS TONATIUH CASTELLANOS SERRANO', 'ubpp_id' => 22, 'proy_ptal' => 608,
            ],
            ['centro' => 83, 'nombre' => 'Centro de investigación en agricultura orgánica (ciao)',
            'coordinador' => 'DRA. MARIA SOL ROBLEDO Y MONTERRUBIO', 'ubpp_id' => 11, 'proy_ptal' => 611,
            ],
            ['centro' => 84, 'nombre' => 'Centro de investigación en gestión de la agroecología (ciga)',
            'coordinador' => 'DRA. MARÍA VIRGINIA GONZALEZ SANTIAGO', 'ubpp_id' => 42, 'proy_ptal' => 614,
            ],
            ['centro' => 85, 'nombre' => 'Centro de investigación, desarrollo y educación en agricultura multifuncional para el desarrollo sostenible.',
            'coordinador' => 'DR. JULIO BACA DEL MORAL', 'ubpp_id' => 31, 'proy_ptal' => 616,
            ],
            ['centro' => 86, 'nombre' => 'Centro de investigación en economía y matemáticas aplicadas (ciema).',
            'coordinador' => 'DR. FRANCISCO PEREZ SOTO', 'ubpp_id' => 6, 'proy_ptal' => 617,
            ],
            ['centro' => 87, 'nombre' => 'Centro de investigaciones para el desarrollo de las regiones cafetaleras. (cenidercafe)',
            'coordinador' => 'JOSE GERVASIO PARTIDA SEDAS', 'ubpp_id' => 32, 'proy_ptal' => 620,
            ],
            ['centro' => 88, 'nombre' => 'Centro de investigación y servicio en economis y comercio agropecuario (ciseca).',
            'coordinador' => 'IGNACIO CAAMAL CAUICH', 'ubpp_id' => 6, 'proy_ptal' => 618,
            ],
            ['centro' => 90, 'nombre' => 'Centro de investigación de etnobiología y biodiversidad (cietbio).',
            'coordinador' => 'DR. BENITO REYES TREJO', 'ubpp_id' => 11, 'proy_ptal' => 610,
            ],
            ['centro' => 91, 'nombre' => 'Centro de investigación y transferencia para la sustentabilidad de ecosistemas forestales.',
            'coordinador' => 'JORGE ANTONIO TORRS PEREZ', 'ubpp_id' => 5, 'proy_ptal' => 619,
            ],
            ['centro' => 92, 'nombre' => 'Centro de investigacion en innovaciones agroalimentarias del tropico (ciiat)',
            'coordinador' => 'ROBERTO GONZALEZ GARDUÑO', 'ubpp_id' => 37, 'proy_ptal' => 609,
            ],
            ['centro' => 210, 'nombre' => 'Alimentación de personas, tesistas urusse y cruo.',
            'coordinador' => 'RODRIGUEZ DE LA O JOSE LUIS', 'ubpp_id' => 29, 'proy_ptal' => 210,
            ],
            ['centro' => 501, 'nombre' => 'Direccion de investigación y posgrado',
            'coordinador' => 'DGIP', 'ubpp_id' => 29, 'proy_ptal' => 501,
            ],
            ['centro' => 541, 'nombre' => 'Acondicionamiento del edificio para el laboratorio central universitario',
            'coordinador' => 'ALEJANDRO BARRIENTOS PRIEGO', 'ubpp_id' => 29, 'proy_ptal' => 541,
            ],
            ['centro' => 596, 'nombre' => 'RM 2016: Proyecto electrico para el lanisaf y su certificacion',
            'coordinador' => 'ROMO LOZANO JOSE LUIS ', 'ubpp_id' => 29, 'proy_ptal' => 596,
            ],
            ['centro' => 620, 'nombre' => 'Centro de investigación para el desarrollo de las regiones cafetaleras (cidercafe)',
            'coordinador' => 'JUAN GUILLERMO CRUZ CASTILLO', 'ubpp_id' => 32, 'proy_ptal' => 620,
            ],
            ['centro' => 621, 'nombre' => 'Fondo concurrente para proyectos externos ',
            'coordinador' => 'DR. ALEJANDRO FACUNDO BARRIENTOS PRIEGO', 'ubpp_id' => 29, 'proy_ptal' => 621,
            ],
            ['centro' => 622, 'nombre' => 'Promocion de registro de la propiedad intelectual derivada de la investigacion',
            'coordinador' => 'DGIP', 'ubpp_id' => 29, 'proy_ptal' => 622,
            ],
            ['centro' => 623, 'nombre' => 'Dirección de Investigación y Posgrado',
            'coordinador' => 'DR. ALEJANDRO FACUNDO BARRIENTOS PRIEGO', 'ubpp_id' => 29, 'proy_ptal' => 623,
            ],
            ['centro' => 626, 'nombre' => 'Programa de estimulos por ingreso y permanencia en el s.n.i. (incluye isr)',
            'coordinador' => 'LIC. OTILIO GARCIA MUNGUIA ', 'ubpp_id' => 29, 'proy_ptal' => 626,
            ],
            ['centro' => 632, 'nombre' => 'Proyectos estrategicos institucionales',
            'coordinador' => 'M.C. CORLAY CHEE LANGEN', 'ubpp_id' => 29, 'proy_ptal' => 632,
            ],
            ['centro' => 636, 'nombre' => 'Direccion de investigacion y posgrado',
            'coordinador' => 'DGIP', 'ubpp_id' => 29, 'proy_ptal' => 636,
            ],
            ['centro' => 637, 'nombre' => 'Ponencias en foros cientificos por profesores inv',
            'coordinador' => 'M.C CORLAY CHEE LANGEN', 'ubpp_id' => 29, 'proy_ptal' => 637,
            ],
            ['centro' => 643, 'nombre' => 'Semana de ciencia y tecnologia',
            'coordinador' => 'M.C. ADRIAN LOZANO TOLEDANO', 'ubpp_id' => 29, 'proy_ptal' => 643,
            ],
            ['centro' => 645, 'nombre' => 'Proyectos estrategicos de investigacion',
            'coordinador' => 'M.C. CORLAY CHEE LANGEN', 'ubpp_id' => 29, 'proy_ptal' => 645,
            ],
            ['centro' => 648, 'nombre' => 'Programa de formación de nuevos investigadores',
            'coordinador' => 'ING. CIRIACO AYALA SANCHEZ', 'ubpp_id' => 29, 'proy_ptal' => 648,
            ],
            ['centro' => 650, 'nombre' => 'Desarrollo y transferencia de tecnologia',
            'coordinador' => 'M.C. CORLAY CHEE LANGEN', 'ubpp_id' => 29, 'proy_ptal' => 650,
            ],
            ['centro' => 651, 'nombre' => 'Revistas institucionales.',
            'coordinador' => 'DR. SANTACRUZ DE LEON EUGENIO', 'ubpp_id' => 19, 'proy_ptal' => 651,
            ],
            ['centro' => 652, 'nombre' => 'Apoyo a organizacion de congresos',
            'coordinador' => 'DR. ALEJANDRO FACUNDO BARRIENTOS PRIEGO', 'ubpp_id' => 29, 'proy_ptal' => 652,
            ],
            ['centro' => 722, 'nombre' => 'Laboratorio central universitario (rm2013)',
            'coordinador' => 'DR. ALEJANDRO FACUNDO BARRIENTOS PRIEGO', 'ubpp_id' => 29, 'proy_ptal' => 722,
            ],
            ['centro' => 723, 'nombre' => 'Laboratorio nacional de investigacion y servicio agroalimentario y forestal',
            'coordinador' => 'DRA. ELIZABERH NAVARRO CERON', 'ubpp_id' => 29, 'proy_ptal' => 310,
            ],
            ['centro' => 2713, 'nombre' => 'Sin centro ',
            'coordinador' => 'DRA. ELIZABERH NAVARRO CERON', 'ubpp_id' => 29, 'proy_ptal' => 0,
            ],
        ];

        DB::table('centros')->insert($centros);

    }
}
